### ISSUE TITLE
Admin frontend broken (with v1.13.0)

### ISSUE THREAD

**Issue by Brutus5000** [NodeBB/nodebb-plugin-write-api#113]
I installed the plugin in the latest version 5.5.3 against a freshly installed NodeBB v1.13.0 (no other plugins touched).

When I try to setup a token via the admin app, the browser fails to show the page on Plugins -> Write API.

Error with Chromium:
![NodeBB error Chromium](https://user-images.githubusercontent.com/6843462/69014872-efb76100-098e-11ea-90f1-b36762fa2bb7.png)

Error with Firefox:
![NodeBB error on Firefox](https://user-images.githubusercontent.com/6843462/69014874-f3e37e80-098e-11ea-82a8-f816488b3b3d.png)

Error from NodeBB logs:
> 2019-11-17T22:02:11.382Z [4567/94] - error: /admin/plugins/write-api
Failed to lookup view "admin/plugins/write-api" in views directory "/usr/src/app/build/public/templates" {"view":{"defaultEngine":"tpl","ext":".tpl","name":"admin/plugins/write-api","root":"/usr/src/app/build/public/templates"},"stack":"Error: Failed to lookup view \"admin/plugins/write-api\" in views directory \"/usr/src/app/build/public/templates\"\n    at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)\n    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1012:7)\n    at content (/usr/src/app/src/middleware/render.js:93:15)\n    at /usr/src/app/node_modules/async/dist/async.js:2952:28\n    at replenish (/usr/src/app/node_modules/async/dist/async.js:444:21)\n    at /usr/src/app/node_modules/async/dist/async.js:449:13\n    at eachOfLimit$1 (/usr/src/app/node_modules/async/dist/async.js:475:34)\n    at awaitable(eachOfLimit$1) (/usr/src/app/node_modules/async/dist/async.js:208:32)\n    at eachOfGeneric (/usr/src/app/node_modules/async/dist/async.js:510:16)\n    at eachOf (/usr/src/app/node_modules/async/dist/async.js:555:16)"}

**Comment by Brutus5000** [comment]
Ok, the readme instruction are slightly unprecies. It must be rebuild and restart. Then it works.
