### ISSUE TITLE
error: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by 0312birdzhang** [NodeBB/nodebb-plugin-write-api#125]
plugin version: 5.7.5
nodebb version: 1.13.3

Error occured when call generate token api '/api/v2/users/%s/tokens'

```
2020-05-18T13:20:22.675Z [4567/32473] - error: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/data/NodeBB/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/data/NodeBB/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/data/NodeBB/node_modules/express/lib/response.js:267:15)
    at Object.ErrorHandler.handle (/data/NodeBB/node_modules/nodebb-plugin-write-api/lib/errorHandler.js:25:19)
    at /data/NodeBB/node_modules/nodebb-plugin-write-api/routes/v2/users.js:158:25
    at /data/NodeBB/node_modules/nodebb-plugin-write-api/lib/auth.js:39:4
    at err (/data/NodeBB/node_modules/async/dist/async.js:2955:19)
    at wrapper (/data/NodeBB/node_modules/async/dist/async.js:268:20)
    at iteratorCallback (/data/NodeBB/node_modules/async/dist/async.js:495:17)
    at /data/NodeBB/node_modules/async/dist/async.js:321:20
    at result (/data/NodeBB/node_modules/async/dist/async.js:2953:17)
    at /data/NodeBB/src/promisify.js:46:48
    at cb (util.js:353:39)
    at process._tickCallback (internal/process/next_tick.js:63:19) {"error":{},"stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (_http_outgoing.js:470:11)\n    at ServerResponse.header (/data/NodeBB/node_modules/express/lib/response.js:771:10)\n    at ServerResponse.send (/data/NodeBB/node_modules/express/lib/response.js:170:12)\n    at ServerResponse.json (/data/NodeBB/node_modules/express/lib/response.js:267:15)\n    at Object.ErrorHandler.handle (/data/NodeBB/node_modules/nodebb-plugin-write-api/lib/errorHandler.js:25:19)\n    at /data/NodeBB/node_modules/nodebb-plugin-write-api/routes/v2/users.js:158:25\n    at /data/NodeBB/node_modules/nodebb-plugin-write-api/lib/auth.js:39:4\n    at err (/data/NodeBB/node_modules/async/dist/async.js:2955:19)\n    at wrapper (/data/NodeBB/node_modules/async/dist/async.js:268:20)\n    at iteratorCallback (/data/NodeBB/node_modules/async/dist/async.js:495:17)\n    at /data/NodeBB/node_modules/async/dist/async.js:321:20\n    at result (/data/NodeBB/node_modules/async/dist/async.js:2953:17)\n    at /data/NodeBB/src/promisify.js:46:48\n    at cb (util.js:353:39)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","exception":true,"date":"Mon May 18 2020 21:20:22 GMT+0800 (China Standard Time)","process":{"pid":32473,"uid":1000,"gid":1000,"cwd":"/data/NodeBB","execPath":"/usr/bin/node","version":"v10.19.0","argv":["/usr/bin/node","/data/NodeBB/app.js"],"memoryUsage":{"rss":222392320,"heapTotal":151138304,"heapUsed":139463096,"external":6158475}},"os":{"loadavg":[0.044921875,0.02392578125,0.00244140625],"uptime":25867257},"trace":[{"column":11,"file":"_http_outgoing.js","function":"ServerResponse.setHeader","line":470,"method":"setHeader","native":false},{"column":10,"file":"/data/NodeBB/node_modules/express/lib/response.js","function":"ServerResponse.header","line":771,"method":"header","native":false},{"column":12,"file":"/data/NodeBB/node_modules/express/lib/response.js","function":"ServerResponse.send","line":170,"method":"send","native":false},{"column":15,"file":"/data/NodeBB/node_modules/express/lib/response.js","function":"ServerResponse.json","line":267,"method":"json","native":false},{"column":19,"file":"/data/NodeBB/node_modules/nodebb-plugin-write-api/lib/errorHandler.js","function":"Object.ErrorHandler.handle","line":25,"method":"handle","native":false},{"column":25,"file":"/data/NodeBB/node_modules/nodebb-plugin-write-api/routes/v2/users.js","function":null,"line":158,"method":null,"native":false},{"column":4,"file":"/data/NodeBB/node_modules/nodebb-plugin-write-api/lib/auth.js","function":null,"line":39,"method":null,"native":false},{"column":19,"file":"/data/NodeBB/node_modules/async/dist/async.js","function":"err","line":2955,"method":null,"native":false},{"column":20,"file":"/data/NodeBB/node_modules/async/dist/async.js","function":"wrapper","line":268,"method":null,"native":false},{"column":17,"file":"/data/NodeBB/node_modules/async/dist/async.js","function":"iteratorCallback","line":495,"method":null,"native":false},{"column":20,"file":"/data/NodeBB/node_modules/async/dist/async.js","function":null,"line":321,"method":null,"native":false},{"column":17,"file":"/data/NodeBB/node_modules/async/dist/async.js","function":"result","line":2953,"method":null,"native":false},{"column":48,"file":"/data/NodeBB/src/promisify.js","function":null,"line":46,"method":null,"native":false},{"column":39,"file":"util.js","function":"cb","line":353,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}
2020-05-18T13:20:22.684Z [4567/32473] - error: Cannot set headers after they are sent to the client
2020-05-18T13:20:22.685Z [4567/32473] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2020-05-18T13:20:22.690Z [4567/32473] - info: [app] Web server closed to connections.
2020-05-18T13:20:22.690Z [4567/32473] - info: [app] Live analytics saved.
2020-05-18T13:20:22.697Z [4567/32473] - info: [app] Database connection closed.
2020-05-18T13:20:22.697Z [4567/32473] - info: [app] Shutdown complete.
[cluster] Child Process (32473) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
```

**Comment by 0312birdzhang** [comment]
After revert to 5.5.4 version, it's working again.

**Comment by julianlam** [comment]
@0312birdzhang Thanks for reporting, it looks to be a regression related to the plugin hooks.

**Comment by julianlam** [comment]
> After revert to 5.5.4 version, it's working again.

Are you certain you reverted back that far? 5.5.4 is from Nov 2019.

I cannot reproduce with write-api@5.7.5 and NodeBB@1.13.3.

**Comment by 0312birdzhang** [comment]
Okay, i fixed it by `rm -rf node_modules` and run `npm install`, then `./nodebb build`, it's working now.
