### ISSUE TITLE
cannot find module './src/postTools'

### ISSUE THREAD

**Issue by jamesjjk** [NodeBB/nodebb-plugin-write-api#37]
Hi there,
Running nodebb v0.8.2 after installing the write api, seemed to work on previous versions any fix?

18/9 12:05 [1] - error:  Error: Cannot find module './src/postTools'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-write-api/routes/v1/posts.js:4:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by barisusakli** [comment]
Should be fixed in 3.2.0
